# Site settings
title: 人杰业丰 Viersteine
email: contact@viersteine.com
description: > # this means to ignore newlines until "baseurl:"
  人杰业丰(Viersteine) - 中国最专业的面向IT互联网领域人力资源服务平台
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.viersteine.com" # the base hostname & protocol for your site
twitter_username: null
github_username:  null

# Build settings
markdown: kramdown
