# Site settings
title: 人杰业丰
email: contact@viersteine.com
description: > # this means to ignore newlines until "baseurl:"
  中国最专业的面向IT互联网领域人力资源服务平台，专注服务于创业企业和中高端职业人士，为创业企业提供深度定制HR服务，助力初创企业成功发展。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.viersteine.com" # the base hostname & protocol for your site
twitter_username: null
github_username:  null

# Build settings
markdown: kramdown
